[sdl]
output=surface
fullscreen=false
windowresolution=800x600

[dosbox]
language=
machine=svga_s3
captures=.
memsize=16

[render]
frameskip=0
aspect=false
scaler=none

[cpu]
cycles=3000
cycleup=10
cycledown=20

[mixer]
nosound=false
rate=22050

[autoexec]
# Mount game directory
mount c .
c:
# Set Russian codepage CP866 for Cyrillic display
keyb ru 866
# Run game
K&C.EXE
